---
title: "Propuesta de Portafolio"
output: html_document
params:
  inicio: NA
  fin: NA
  promotor: NA
  nombre: NA
  perfil: NA
  mxpusdeur: NA
  ci_portafolio: NA
  grafica_rendimiento: NA
  ci_summary: NA
  ci_pie: NA
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(webshot)
library(knitr)
library(kableExtra)
nombre <- params$nombre
```

<br>

<span style="font-size: 1.25em;">Portafolio propuesto por **`r params$promotor`** para **`r params$nombre`**</span>

<br>

```{r, fig.show='hold', fig.height = 3, fig.width = 5}
#Posiciones de los portafolios
p1 <- params$ci_portafolio
p2 <- params$otro_portafolio
fixed_percent1 <- sum(p1$Porcentaje[ifelse(substr(p1$Fondo,1,2) == "51", TRUE, FALSE)])
fixed_percent2 <- sum(p2$Porcentaje[ifelse(substr(p1$Fondo,1,2) == "51", TRUE, FALSE)])

params$ci_summary %>%
  kable(booktabs = TRUE, format = "html", align <- c("r","l")) %>%
  kable_styling(latex_options = "striped", position = "float_right", full_width = FALSE, font_size = 15) %>%
  column_spec(1, bold = TRUE)

params$ci_pie

```

<br>

<span style="font-size: 1.25em;">Se propone un portafolio compuesto de `r paste0(fixed_percent1*100,"%")` **deuda** y `r paste0((1-fixed_percent1)*100,"%")` de **renta variable** para un perfil **`r tolower(params$perfil)`**.</span>

---

<span style="font-size: 1.25em;">Rendimientos de la propuesta</span>

del `r format(params$inicio, '%d de %B del %Y')` al `r format(params$fin, '%d de %B del %Y')`


```{r, fig.show='hold', fig.height = 3.5, fig.width = 5}

params$mxpusdeur %>%
  kable(booktabs = TRUE, format = "html", align <- c("r","l")) %>%
  kable_styling(latex_options = "striped", position = "float_right", full_width = FALSE, font_size = 12) %>%
  column_spec(1, bold = TRUE)

params$grafica_rendimiento

```
